#!/usr/bin/env python3
"""
Convert a fixed-width BDF bitmap font into a C table for the display console
(components/esp_display). Run by the build; the output is never committed, and
the font itself comes from a vendored archive (third_party/, e.g. Spleen).

    bdf2c.py FONT.bdf OUT.c

The table holds one glyph per code point, sorted, each as `height` rows of
`width` bits (most significant bit leftmost; widths up to 8). Glyphs are placed
in the cell by their bounding boxes, so fonts whose glyphs don't all fill the
font's box still line up on the baseline.
"""

import sys


def parse(path):
    glyphs, font_box = {}, None
    enc = bbx = rows = None
    with open(path, encoding="latin-1") as f:
        for line in f:
            w = line.split()
            if not w:
                continue
            if w[0] == "FONTBOUNDINGBOX":
                font_box = tuple(int(x) for x in w[1:5])
            elif w[0] == "ENCODING":
                enc = int(w[1])
            elif w[0] == "BBX":
                bbx = tuple(int(x) for x in w[1:5])
            elif w[0] == "BITMAP":
                rows = []
            elif w[0] == "ENDCHAR":
                if enc is not None and enc >= 0 and bbx is not None:
                    glyphs[enc] = (bbx, rows)
                enc = bbx = rows = None
            elif rows is not None:
                rows.append(int(w[0], 16))
    return font_box, glyphs


def main(src, out):
    (fw, fh, fx, fy), glyphs = parse(src)
    if fw > 8:
        sys.exit(f"bdf2c: {src}: glyphs wider than 8 pixels are not supported")
    table = []
    for cp in sorted(glyphs):
        (gw, gh, gx, gy), rows = glyphs[cp]
        nbytes = (gw + 7) // 8
        cell = [0] * fh
        top = fh - (gy - fy) - gh              # glyph's top row within the cell
        for r, bits in enumerate(rows):
            y = top + r
            if 0 <= y < fh:
                # left-align the glyph's bits in a byte, then shift by its x offset
                v = bits >> (8 * nbytes - 8) if nbytes > 1 else bits
                v = (v >> (gx - fx)) & 0xFF if gx >= fx else (v << (fx - gx)) & 0xFF
                cell[y] = v
        table.append((cp, cell))
    with open(out, "w") as o:
        o.write(f"/* Generated by scripts/bdf2c.py from {src.split('/')[-1]}; do not edit. */\n")
        o.write('#include "esp_display_font.h"\n\n')
        o.write(f"const esp_display_font_t esp_display_font = {{\n"
                f"    .width = {fw}, .height = {fh}, .count = {len(table)},\n"
                f"    .codepoints = (const uint32_t[]){{\n")
        for i in range(0, len(table), 8):
            o.write("        " + " ".join(f"0x{cp:04x}," for cp, _ in table[i:i + 8]) + "\n")
        o.write("    },\n    .bitmaps = (const uint8_t[]){\n")
        for cp, cell in table:
            o.write("        " + " ".join(f"0x{b:02x}," for b in cell) + f"  /* U+{cp:04X} */\n")
        o.write("    },\n};\n")


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
