#!/usr/bin/env python3
"""
Convert a fixed-width BDF bitmap font into a C table for the display console
(components/esp_display). Run by the build; the output is never committed, and
the font itself comes from a vendored archive (third_party/, e.g. Spleen).

    bdf2c.py FONT.bdf OUT.c [SYMBOL [NAME]]
                          (SYMBOL: default esp_display_font; NAME, as :EspFont
                           shows it: default the BDF file's name)

The table holds one glyph per code point, sorted, each as `height` rows of
`width` bits, one byte per row for widths up to 8 and two (big-endian) up to 16,
most significant bit leftmost. Glyphs are placed in the cell by their bounding
boxes, so fonts whose glyphs don't all fill the font's box still line up on the
baseline.
"""

import sys


def parse(path):
    glyphs, font_box = {}, None
    enc = bbx = rows = None
    with open(path, encoding="latin-1") as f:
        for line in f:
            w = line.split()
            if not w:
                continue
            if w[0] == "FONTBOUNDINGBOX":
                font_box = tuple(int(x) for x in w[1:5])
            elif w[0] == "ENCODING":
                enc = int(w[1])
            elif w[0] == "BBX":
                bbx = tuple(int(x) for x in w[1:5])
            elif w[0] == "BITMAP":
                rows = []
            elif w[0] == "ENDCHAR":
                if enc is not None and enc >= 0 and bbx is not None:
                    glyphs[enc] = (bbx, rows)
                enc = bbx = rows = None
            elif rows is not None:
                rows.append(int(w[0], 16))
    return font_box, glyphs


def main(src, out, symbol="esp_display_font", name=None):
    (fw, fh, fx, fy), glyphs = parse(src)
    if fw > 16:
        sys.exit(f"bdf2c: {src}: glyphs wider than 16 pixels are not supported")
    bpr = 1 if fw <= 8 else 2               # bytes per row
    mask = (1 << (8 * bpr)) - 1
    if name is None:
        name = src.split("/")[-1].rsplit(".", 1)[0]
    table = []
    for cp in sorted(glyphs):
        (gw, gh, gx, gy), rows = glyphs[cp]
        nbytes = (gw + 7) // 8
        cell = [0] * fh
        top = fh - (gy - fy) - gh              # glyph's top row within the cell
        for r, bits in enumerate(rows):
            y = top + r
            if 0 <= y < fh:
                # the glyph's bits, left-aligned in a row of bpr bytes, then
                # shifted by the glyph's x offset in the cell
                v = bits << (8 * (bpr - nbytes)) if nbytes <= bpr else bits >> (8 * (nbytes - bpr))
                v = (v >> (gx - fx)) & mask if gx >= fx else (v << (fx - gx)) & mask
                cell[y] = v
        table.append((cp, cell))
    with open(out, "w") as o:
        o.write(f"/* Generated by scripts/bdf2c.py from {src.split('/')[-1]}; do not edit. */\n")
        o.write('#include "esp_display_font.h"\n\n')
        o.write(f"const esp_display_font_t {symbol} = {{\n"
                f"    .name = \"{name}\",\n"
                f"    .width = {fw}, .height = {fh}, .bytes_per_row = {bpr}, .count = {len(table)},\n"
                f"    .codepoints = (const uint32_t[]){{\n")
        for i in range(0, len(table), 8):
            o.write("        " + " ".join(f"0x{cp:04x}," for cp, _ in table[i:i + 8]) + "\n")
        o.write("    },\n    .bitmaps = (const uint8_t[]){\n")
        for cp, cell in table:
            b = [x for v in cell for x in (((v >> 8) & 0xFF, v & 0xFF) if bpr == 2 else (v,))]
            o.write("        " + " ".join(f"0x{x:02x}," for x in b) + f"  /* U+{cp:04X} */\n")
        o.write("    },\n};\n")


if __name__ == "__main__":
    main(*sys.argv[1:5])
